name 'objectiflibre-puppet'
version '0.0.21'
source 'git://github.com/ObjectifLibre/puppet-puppet.git'
author 'Guillaume Espanel'
description 'Resource types for managing puppet master and agent'
summary 'Resource types for managing puppet master and agent'
license 'Apache'
project_page 'https://github.com/ObjectifLibre/puppet-puppet'
## Add dependencies, if any:
dependency 'puppetlabs/inifile', '>= 1.0.0'
dependency 'puppetlabs/apache', '>= 0.8.0'
dependency 'puppetlabs/puppetdb', '>= 2.0.0'
